pygments: true

title : brandoamplification.com
url : http://brandoamplification.com
author :
  name : Brando Andersen
  github : brandoamplication
  
exclude: ["bower_components", "bower.json", "Gruntfile.js", "node_modules"]
